language: ruby
rvm:
- 2.3.3
before_install:
- rvm install 2.3.3
install:
- bundle install --path vendor/bundle
script:
- git config --global user.name '${GH_NAME}'
- git config --global user.email '${GH_EMAIL}'
- git remote set-url origin https://fcatuhe:${GH_TOKEN}@github.com/fcatuhe/mvp1day.git
- bundle exec middleman deploy
branches:
  only:
  - master
env:
  global:
  - secure: ZPRMSXVv/brMzSz86nJBfVOf7A1M9NSDJlVlPycco0YJbVoYZgHX6E5AvGlDpQg2GqtYbH+kQPgSwzSFpEgw3C34S3U6zL5Uf02Mee9+RXFwgPqwU81bHc4s4PmztCIB3DpmHWLP7BzAzelPjXV3VEL3OKwhiYoHZoTrhtDmqgplwTbLOuDFTVYAMUVgsvjvIKu8JGbCYmhI8UdAYauK2EnMZ5AQD9KKK5wNCaJAeFdncPM54od0NYwi3l6ONcuad0HB7Py6HPw9IzZBfNsH1ndo22pp/oWLBW+Cg/kk+p+O0fGcIz9lsGpmSR6smv7EUEUzHTnqyB4d9XGw036cMEW8AmmmRI+/Nblvx4zubNwy3DsFJHWMIaafoIjVT5fWqUao9Z5JWunysoDpdZAIHHBVivVvWnC118czWgvGvunFjQV6WWJHWPJlgKCwtl6P2KHzUYEgFPXfsI6vyvLq2btL8sM1XLKM5IL+psRPO2MtKigBvCZD+i0jOZ67ppeS/iAkUMy1Enwr0RyJ7BkP9j+punG/HvzWkg02oTf00X22hc+LLgzjmC7RYxh6bZPiCNSwf6GnpjRPBT2/R80g1idC3En7Ajz7hfVhA4dtQs6LRNNevfzxWNmpgKrfSGQQ7TJFDHN4OqHmVc5Vk9QS6lt6sLbLITLqbfApGnyajSQ=
  - secure: WN5Z/lucENfWWrWf6Igne2BRnNNAJAKYVA8hAkXlYEz8i25pvgq8pJAQ1a9YBdLkfHhGoUS82biv+W0Hg2otmHgsgqfzXOeG5BKzXKqJM113zJ00hWprjo9Nlh/BuUN3EmbBVFMBApvfJOrJXD5N8vdf+mB0S+cV5Y9Va6eHETQpMTBclWCMTsLNxYvv39osOfq7fODhX+fJAx4TtQBn9wbmBlTLy6r/FiuMGgl9EoToYqyD+0JTqRND9hPxigk5O+Au//8BDVgBzN4qsILAhXqoC/4AqgmONRqPa40bhZDYx3kl1J8WyFBfQI6JH0HS3arzhx1qGhZmW/RTYWZbKTNkna+cRB/WaoyK8Y3KNEeOCvXscNpdQnu6vp43c6mMTlf/Ql3H7CRIqcd+OIHnzVA5Pa9pUeJP72lS6gm16BL7pZQ8vsf/SDvkSSghIyo5x8u51f6NsTML9pBVl7CXMcGVDCaXKHqPUUU29M61fxVf1iV+FUK8Leq5/ToxTqvUiQihXoiP4CLtleYVIOZShMorfvLSed6rg8kc4uS4Y+xcCoNMfhhgyWkBrsOKqZhXHTgyf+kH5qvfR+6PHkY9H/N3Lpp+6y0pCUbyIwRFPX4c+3Ny12pvUNRS70wNB+m2148I3hAswo9iVOeihjI30V8KYLH8m0GaXWPSqpjex2g=
  - secure: KttiqSKVYhpyjy+d2VHcnaeYEWDKFZOwbyvGCpXLYS7GiH2H10MTRpasiH4k2k/Hh8ceIIBKsYF/114vyIMLTqT/J7Lv8CsboLYPXs/wecPVwhQwHJ/1a6l0EUWN78EgyAdj8rnBCUqU+eyppMhUFm469ZbproPvz/elCts4ttG1juH6Lq6TgTqZlqbANvX3kKf51E/GPEBUXjlgZtX6DMCVZL2hTk8NepEaIP5kHOOr/Dm/B6Vx405wdDnO4tKt0ned5LOm8HBKBjh+kwxByW7k+Z6ZfDFTOPkUkH4KzOguWGN3SCjGibphziDSFoZ5nLINdkCtvKDJVFD6hTNnburpPpsDWaP5dkkPPmAy42lCrNfJhilp2JdLhk0aZ4/oBTXBSy8+FJeiMUTO0iQH3Gk1x8NWG4B0Pa05KaV0zxUqXB/b43hiHtuDC/bgYgS4bssUA9W3Ci2E1ocnTdrT06ZwdFl6gtIL0pL8uQ5LTDQCOZaubTZVYgMZnf62lf0s+EmL7yY3SRXXtEgG3b/Mz5k8zPbGU6Ay/FIf5mbad+/Bug+6rC2GpedIAhdx+3436sErL3Ho5RNC3kU8mPjwYynqQLmMrKOKbvbIOi28oSOk84YH2jm5OrHubkvqL4rRXAzPbqEv6zFBKnTtgaTmOGNVEEVyIfSKAmb8NfWAOBs=
