language: ruby
rvm:
- 2.3.3
before_install:
- rvm install 2.3.3
install:
- bundle install --path vendor/bundle
script:
- git config --global user.name '${GIT_NAME}'
- git config --global user.email '${GIT_EMAIL}'
- git remote set-url origin https://fcatuhe:${GH_TOKEN}@github.com/fcatuhe/mvp1day.git
- bundle exec middleman build
- bundle exec middleman deploy
branches:
  only:
  - master
env:
  global:
  - secure: xSnUnETFBXsRQCSYjAzhIh24WBC0qqsFrepP1QN1YE26R96S0k+nWS4/BUiSCUczYvs79A1kL9Znrt7RXYXsH1ceZUad5xxTStdLlHl1KO3B4HrDNS2T5o3ha/E2aV7Q7k+Hm2Dee0yy8aN0COlG3w5Dd5mUObA+/WW+os7HR0kW7j2XNwZ6Y8hSWb3MmAzpRrvrxOkAIZy6YRpNqd+LxtuhLJZPfJgp7RaAhOCmR61hsdItyfhhstkFOxgp3fo88Yrv2Ix/nkGY4OPbOqIUm1DQTej/YH3t24i2Z82EkdZwumyjz3Z82rBYpGoPCFBMltjSazR62AUve/xXDjCyGE73BYrXnm1Vi//DImax+bW68WqiA5moSvH9W23r6rsEi+33epWjCquosRVU7xytBH6sh8dbyvr9XLpl0lZH4h2ZUkThqxc8fO3hhyFuYCVIF9Zx3dGlYEH4GoOKjyR00Sxh7pYRx+SNQLvQn1SWbZPgqHm4SzlPxPr1xBGCOZmO8qKhF5I7GEst+9kCZUziAJR7mlyH2GsUYDRLE47qEhDrmjodrD5nIWXNECUwA8MleANg0HRM0gQoWY2KLfX2FY7RZ4N1mhmFgT9zGB1Pu3Xm0pHjMpsqWFv1hH+IjPYQW/8JzJC0sJeL7LeA+yRZR32rNpXnHafXoo1XTux9D1Q=
  - secure: GPQGOe8/JiNX4VbBm7X+H0Efjp5xir1SWme/uUWU+PfE8iWE3qV52JrtThH4n+WnNEqZPshEDR3l+DR7vrB36amtAzrh3ZLOtWuatpo4E79CDAlDXOvLN2COtoxr6lLjhXPffIFNaaR1r8ft8GrqdMRw5gFL3ZHhVxXHKRvqi5383Dv4VpyS70d8tndd3SMbNSqlMANO9HZtOGjcPLmMxS9PX8fUdnWHqIy5sVmoqoTcwaSPpv7lJ4qGxsILgJ/3kq6FVcMHEfiVWciCXd7a4aOlH6OVjngGZ7FtqgJJVRz5tPDeivvGJkMfTbiNIJI9fS8i3q7nNcJsiqf/zk+V0+K2o5VTR2thJxm/F0JOsM7JhNZtOjGJtEL9swcOHHiyQWbco5l47vGjY9l13FsfxYyhnRW0kx79mDkgMyUi1EouKmeLxCBL/x+cFpzfx6J9ZX7OIdNBAnFV0dIT8juui0WYnVGBLNo7mp+IhZ01of59Xhg7GdYsidETdXReYDMW8j2PZyZRAwMP+LsLAxsJx9zVCqNEGTnwh4PxiEovloGZgFoAtGSqW8PPAiiIURnUKxXBKvF+dSWxLy0AC1x3Ytqp6L3hT6CkzriUtC0r/MhV6J7UjXhMhCHCUMRChTmQnWW0NbVM2P67rVfMCFq3sk5gdSABf6awaHjInvxRyRk=
  - secure: KttiqSKVYhpyjy+d2VHcnaeYEWDKFZOwbyvGCpXLYS7GiH2H10MTRpasiH4k2k/Hh8ceIIBKsYF/114vyIMLTqT/J7Lv8CsboLYPXs/wecPVwhQwHJ/1a6l0EUWN78EgyAdj8rnBCUqU+eyppMhUFm469ZbproPvz/elCts4ttG1juH6Lq6TgTqZlqbANvX3kKf51E/GPEBUXjlgZtX6DMCVZL2hTk8NepEaIP5kHOOr/Dm/B6Vx405wdDnO4tKt0ned5LOm8HBKBjh+kwxByW7k+Z6ZfDFTOPkUkH4KzOguWGN3SCjGibphziDSFoZ5nLINdkCtvKDJVFD6hTNnburpPpsDWaP5dkkPPmAy42lCrNfJhilp2JdLhk0aZ4/oBTXBSy8+FJeiMUTO0iQH3Gk1x8NWG4B0Pa05KaV0zxUqXB/b43hiHtuDC/bgYgS4bssUA9W3Ci2E1ocnTdrT06ZwdFl6gtIL0pL8uQ5LTDQCOZaubTZVYgMZnf62lf0s+EmL7yY3SRXXtEgG3b/Mz5k8zPbGU6Ay/FIf5mbad+/Bug+6rC2GpedIAhdx+3436sErL3Ho5RNC3kU8mPjwYynqQLmMrKOKbvbIOi28oSOk84YH2jm5OrHubkvqL4rRXAzPbqEv6zFBKnTtgaTmOGNVEEVyIfSKAmb8NfWAOBs=
